spring.application.name=fields


## Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/exodus_db
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

## Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=8080
spring.data.redis.password=admin

## JWT configuration
jwt.secret=z4q2GjxZBml5HLD4pyi33YyjFLAJSmThj8zfvH0oE8Y=
